version: "3.9"

services:
  pytorch-jupyter:
    build:
      context: .  # Dockerfile이 위치한 디렉토리
    container_name: pytorch_jupyter_lab
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - .:/workspace
    working_dir: /workspace
    ports:
      - "8888:8888"
    stdin_open: true
    tty: true